### ISSUE TITLE
FE - dlha funkcia

### ISSUE THREAD

**Issue by katarinaHrab** [AppsLab-2/parking-app#2]
Hrozne dlha funkcia. Clovek sa straca v tom, co to vlastne robi. Rozdelila by som na viacero funkcii a tie potom volala v tejto hlavnej. Pripadne by som si vytvorila util triedu, kde by som robila tieto detaily a v service ponechala iba volanie rest endpointu.

https://github.com/AppsLab-2/parking-app/blob/7d228b1172461131ae4aea5f03638f451e2fc1c7/Frontend/src/app/place.service.ts#L15

**Comment by KultanJuraj** [comment]
Ďakujem za upozornenie, v poslednej dobe sa necítim moc dobre, ale snažím sa FE pracovať najviac ako dokážem, tú funkciu som už trochu zjednodušil a dnes by som to mal aj pushnut.
