### ISSUE TITLE
FE - pisanie viac slovnych nazvov

### ISSUE THREAD

**Issue by katarinaHrab** [AppsLab-2/parking-app#4]
Je to sice drobnost ale podla mna dobra vizitka programatora...nazvy zacinaju s malym pismenkom a pokial su viac slovne, kazde dalsie slovo zacina velkym pismenkom

https://github.com/AppsLab-2/parking-app/blob/7d228b1172461131ae4aea5f03638f451e2fc1c7/Frontend/src/app/book-formular/book-formular.component.ts#L40

**Comment by KultanJuraj** [comment]
Nie som moc zvyknutý písať viac slovné názvy, ale snažím sa na to zvyknúť a v budúcnosti si budem na to dávať väčší pozor.
