### ISSUE TITLE
FE - co robi tato metoda??

### ISSUE THREAD

**Issue by katarinaHrab** [AppsLab-2/parking-app#5]
Tak tu som sa uplne stratila, co robi tato metoda. Komentare v kode by neuskodili. Snazila som sa zistit, ci tu nerobite nieco, co uz je dostupne v nejakej verejnej kniznici.

https://github.com/AppsLab-2/parking-app/blob/7d228b1172461131ae4aea5f03638f451e2fc1c7/Frontend/src/app/dashboard/dashboard.component.ts#L22

**Comment by KultanJuraj** [comment]
Táto funkcia určuje momentálny čas a podľa toho vyberá z dvojrozmerného array booleanov a podľa toho sa zobrazí parkovacie miesto na zelene alebo na červeno.

**Comment by KultanJuraj** [comment]
A ešte som zabudol povedať, že v budúcnosti sa pokúsim používať viac komentárov v mojom kóde.
