### ISSUE TITLE
FE - isiel by pouzit nejaky cyklus?

### ISSUE THREAD

**Issue by katarinaHrab** [AppsLab-2/parking-app#6]
Toto opakovanie je celkom drsne. Myslite, ze by to slo zjednodusit/skratit cyklom?

https://github.com/AppsLab-2/parking-app/blob/7d228b1172461131ae4aea5f03638f451e2fc1c7/Frontend/src/app/detail-page/detail-page.component.html#L15

**Comment by KultanJuraj** [comment]
Už som tam použil cyklus ngFor aby to bolo o niečo kratšie.
